language: c
notifications:
  email: true
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential subversion git autoconf libtool texinfo python-lxml valgrind
 - svn checkout https://svn.code.sf.net/p/check/code/trunk check-code
 - cd check-code
 - autoreconf --install
 - ./configure
 - make
 - sudo make install
 - sudo ldconfig
 - cd ..
script: ./autogen.sh && ./configure && make && make check
