language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "daDBy/1RrqpWonB1RnRlrKSFUsiG4dOPWwBz/2bnhtiULD0Ghf9yvMpN0Ji2ofXyiPQvmf6LO6pCkKtWjvMgUKNzMl7svooXi5xxwSNcpXphoSzI88wpB9ANjzOC4ZrLzQHteodeVsiYr2j7TGaVenRpZRH5SuZjSzSqLnFR6Og="

addons:
  coverity_scan:
    project:
      name: "acplt/open62541"
      description: "Open-source OPC UA"
    notification_email: 
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: coverity_scan

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential subversion git autoconf libtool texinfo python-lxml valgrind
 - svn checkout https://svn.code.sf.net/p/check/code/trunk check-code
 - cd check-code
 - autoreconf --install
 - ./configure
 - make
 - sudo make install
 - sudo ldconfig
 - cd ..
script: ./autogen.sh && ./configure && make && make check
