version: '{build}'
os: Visual Studio 2015 RC
clone_folder: c:\projects\open62541
environment:
    global:
        CYG_ROOT: C:/cygwin
before_build:
- set STATICBUILD=true && python -m pip install lxml
build_script:
- cd c:\projects\open62541
- md build
- cd build
- echo "Testing cygwin"
- cmd: '%CYG_ROOT%/bin/bash --login -lc "export PATH=/cygdrive/c/Python27/:$PATH; export PYTHONUNBUFFERED=1; cd /cygdrive/c/projects/open62541/build; cmake -DUA_BUILD_EXAMPLESERVER:BOOL=ON -DCMAKE_COMPILER_IS_GNUCC:BOOL=ON -DUA_BUILD_EXAMPLECLIENT:BOOL=ON -DUA_BUILD_EXAMPLES:BOOL=ON -G\"Unix Makefiles\" ..; make'
- cd ..
- rd /s /q build
- md build
- cd build
- cmake -DUA_BUILD_EXAMPLESERVER:BOOL=ON -DUA_BUILD_EXAMPLECLIENT:BOOL=ON -DUA_BUILD_EXAMPLES:BOOL=ON -G"Visual Studio 12 2013" ..
- msbuild open62541.sln
- echo "Testing amalgamation"
- cd ..
- rd /s /q build
- md build
- cd build
- cmake -DUA_BUILD_EXAMPLESERVER:BOOL=ON -DUA_BUILD_EXAMPLECLIENT:BOOL=ON -DUA_BUILD_EXAMPLES:BOOL=ON -DUA_ENABLE_AMALGAMATION:BOOL=ON -G"Visual Studio 12 2013" ..
- msbuild open62541.sln 
- cp C:\projects\open62541\build\open62541.c C:\projects\open62541\build\Debug\open62541.c
- cp C:\projects\open62541\build\open62541.h C:\projects\open62541\build\Debug\open62541.h
- cd ..
- echo "Win 64 build"
- md build64
- cd build64
- cmake -DUA_BUILD_EXAMPLESERVER:BOOL=ON -DUA_BUILD_EXAMPLECLIENT:BOOL=ON -DUA_BUILD_EXAMPLES:BOOL=ON -DUA_ENABLE_AMALGAMATION:BOOL=ON -G"Visual Studio 12 2013 Win64" ..
- msbuild open62541.sln 
- cp C:\projects\open62541\build64\open62541.c C:\projects\open62541\build64\Debug\open62541.c
- cp C:\projects\open62541\build64\open62541.h C:\projects\open62541\build64\Debug\open62541.h
- cd ..
after_build:
- 7z a open62541-win32.zip %APPVEYOR_BUILD_FOLDER%\build\Debug\*
- 7z a open62541-win64.zip %APPVEYOR_BUILD_FOLDER%\build64\Debug\*
- appveyor PushArtifact open62541-win32.zip
- appveyor PushArtifact open62541-win64.zip
